name: Publish Docker Image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker Image To Docker Hub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout The Repo
        uses: actions/checkout@v4.2.2

      - name: Login To Docker Hub Account
        uses: docker/login-action@v3.3.0
        with:
          registry: registry.b-rayz.ch
          username: ${{secrets.BRAYZ_REGISTRY_USERNAME}}
          password: ${{secrets.BRAYZ_REGISTRY_PASSWORD}}

      - name: Extract Metadata (Tags, Labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: registry.b-rayz.ch/fahad/user-dir-ui

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
